# Generated by Django 4.0.3 on 2023-07-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
