# Generated by Django 4.0.3 on 2023-07-20 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_shoe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='bin_id',
        ),
    ]
