# Generated by Django 4.0.3 on 2023-07-20 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0003_remove_shoe_bin_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoe',
            options={'ordering': ('manufacturer', 'model_name')},
        ),
    ]
