# Generated by Django 4.0.3 on 2023-07-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_binvo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='bin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='shoes_rest.binvo'),
            preserve_default=False,
        ),
    ]
