# Generated by Django 4.0.3 on 2023-07-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0007_remove_shoe_bin_delete_binvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
    ]
