# Generated by Django 4.0.3 on 2023-07-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0010_shoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='bin_href',
            new_name='import_href',
        ),
    ]
