# Generated by Django 4.0.3 on 2023-07-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0012_rename_color_shoe_shoecolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='shoeColor',
            new_name='shoe_color',
        ),
    ]
